version: '3.8'

services:
  mysql-db:
    image: mysql:8
    container_name: configuration-management-system-backend-mysql-db-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: sodatech_db
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 20s

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mysql-db

  config-service:
    build:
      context: .
      dockerfile: config-service/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mysql-db



